### ISSUE TITLE
Added source files cannot import pod modules

### ISSUE THREAD

**Issue by gazialankus** [asmallteapot/cocoapods-playgrounds#39] opened 2016-09-01 21:52 UTC
I like to separate my playground code into many files. In a regular playground, I place swift files in the Sources folder under the playground and I can use their public classes and functions in the playground code. 

In a playground with pods, it seems **only** the main playground code is able to import modules coming from pods. I tried adding swift files to the Sources folder under the playground and adding swift files to the project main folder as a sibling to the playground, in both cases I cannot import the pod modules. 

Please let me know if I'm missing something. If not, it would be great if you could fix this.

**Comment by neonichu** [comment] 2016-09-01 21:55
Unfortunately, this is a limitation of Xcode itself. There should be a duplicate of this issue in the closed ones which references a radar you can dupe.

**Closed as completed** 2016-09-01 21:55 UTC

**Comment by gazialankus** [comment] 2016-09-01 21:57
Sorry about that. I found the dup for future reference: https://github.com/neonichu/ThisCouldBeUsButYouPlaying/issues/21

**Comment by neonichu** [comment] 2016-09-01 22:01
Thanks for linking it!
