### ISSUE TITLE
Needed to manually add pod framework to get linked in

### ISSUE THREAD

**Issue by github-user32** [asmallteapot/cocoapods-playgrounds#25] opened 2016-06-02 06:15 UTC
Just installed cocoapods-playgrounds-1.2.0. 
Then ran:
`pod playgrounds DateTools`
After opening the workspace in Xcode 7.3.1, I built the DateToolsPlayground schema.
If I then open the playground, the line `import DateTools` has a compiler error "No such module 'DateTools'".

It was easily fixed by dragging the Frameworks/DateTools.framework to the DateToolsPlayground target's 'Linked frameworks and libraries'. It would be great if you could add this last step so no manual intervention was required.

(Aside, thanks for the handy tool!)

**Comment by neonichu** [comment] 2016-06-02 06:45
Hm, that last step should not be needed. Did you try deleting DerivedData? :)

**Comment by github-user32** [comment] 2016-06-02 07:06
OK, just tried that, but it doesn't make any difference. (Also tried completely removing the generated workspace and running 'pod playgrounds DateTools' from afresh - same problem.)

**Comment by neonichu** [comment] 2016-06-02 21:56
I wasn't able to reproduce this. I'm thinking you might be on an older version of `cocoapods-playgrounds` while using CocoaPods 1.0 at the same time.

**Comment by github-user32** [comment] 2016-06-02 23:25
Thanks for trying it out. It is tricky if you can't reproduce it. This is my configuration...I think it's up to date:

```
$ xcodebuild -version
Xcode 7.3.1
Build version 7D1014
$ pod --version
1.0.0
$ gem list cocoapods-playgrounds

*** LOCAL GEMS ***

cocoapods-playgrounds (1.2.0)
```

I was running `pod playgrounds DateTools` from in /tmp/, but same result from other directories too.

Is there any debug tracing/logging I can enable that might help?

**Comment by neonichu** [comment] 2016-06-02 23:43
Could you paste the `Podfile` of your generated Playground directory? Just to make sure that the right version of the plugin is used at runtime and rule that out.

**Comment by github-user32** [comment] 2016-06-02 23:57
Sure. I think this is what you're after:

```
$ cat DateToolsPlayground/Podfile
use_frameworks!

target 'DateToolsPlayground' do
pod 'DateTools'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end
```

**Comment by neonichu** [comment] 2016-06-03 01:25
Looks right — did you try actually just going ahead and use the framework, ignoring the error shown inside the Playground? It sometimes happens that the error will still be shown even though everything is alright until the framework is actually used.

**Comment by github-user32** [comment] 2016-06-03 01:40
Just tried your suggestion with this in the playground:

```
//: Please build the scheme 'DateToolsPlayground' first
import XCPlayground
XCPlaygroundPage.currentPage.needsIndefiniteExecution = true

import Foundation
import DateTools

let date = NSDate.init(timeIntervalSinceNow: -3700)
date.timeAgoSinceNow()
```

It doesn't work, in a way that's consistent with the framework not being linked in. The playground shows an error `Execution was interrupted, reason: signal SIGABRT`
and the debugger console shows:
`-[__NSDate timeAgoSinceNow]: unrecognized selector sent to instance 0x7faaa2e10c50`

**Comment by neonichu** [comment] 2016-06-03 01:51
OK, it was just a thought because I have been confused by the sometimes sticky error messages before :). Unfortunately, I'm running out of ideas of what the issue could be here.

**Comment by github-user32** [comment] 2016-06-03 02:01
I know what you mean about the sticky error messages. No worries if you can't work out what might be going on. There must be something different about my configuration, but it could be pretty hard to track down. Is it worth just closing this issue then until we come up with anything further?

**Comment by neonichu** [comment] 2016-06-03 02:05
Yah, let's close it for now, but feel free to report back with new information if you have any.

**Closed as completed by neonichu** 2016-06-03 02:05 UTC

**Comment by github-user32** [comment] 2016-06-03 02:10
All good. Thanks for looking into it.
