### ISSUE TITLE
broken with CocoaPods 1.0.0

### ISSUE THREAD

**Issue by icanzilb** [asmallteapot/cocoapods-playgrounds#22] opened 2016-05-13 09:36 UTC
After upgrading to CP 1.0.0 the playground produced by the plugin can't find it's pods, like so:

`pod playground RealmSwift` ->

![image](https://cloud.githubusercontent.com/assets/633862/15243944/f43579b2-18fe-11e6-9e00-2f7bb2c813a9.png)

**Comment by neonichu** [comment] 2016-05-13 10:30
:scream:

**Comment by neonichu** [comment] 2016-05-13 10:33
This is caused by the scoping of product build directories done in CP 1.0, the `RealmSwift.framework` will be in a subdirectory which is not part of the frameworks search path of the Playground. 

I think the best course of action is to add a copy or symlink step to the dummy target we're creating, so that `pod install` or `pod update` would still work within the generated project. Another approach would be copying the frameworks as part of `pod playgrounds` similar to the way it is done right now when using Carthage.

**Comment by icanzilb** [comment] 2016-05-13 10:34
Carthage 😱

**Comment by yurrriq** [comment] 2016-05-14 04:27
@neonichu, can you elaborate on the symlink solution? I'm not sure what to do, but would love to try out your tool.

**Closed as completed** 2016-05-14 20:36 UTC
Labels: bug

**Comment by neonichu** [comment] 2016-05-14 20:42
I just shipped a new release which fixes this: https://github.com/neonichu/ThisCouldBeUsButYouPlaying/releases/tag/v1.0.0

The implementation was actually much easier, I'm just setting `CONFIGURATION_BUILD_DIR` in a `post_install` hook so that it plays nice with Playgrounds.

**Comment by icanzilb** [comment] 2016-05-14 20:45
I installed it 4 minutes ago, but thanks for pinging me 👍 I'm gonna try to find a bit of time tomorrow to look into playing with it, will let you know if all is okay, thanks again for fixing it!

**Comment by yurrriq** [comment] 2016-05-14 21:29
Awesome. Thank you!

**Comment by icanzilb** [comment] 2016-05-15 09:30
great work Boris, all is fine again
