### ISSUE TITLE
Fails to import pod in plaground

### ISSUE THREAD

**Issue by dhf0820** [asmallteapot/cocoapods-playgrounds#27] opened 2016-06-14 19:35 UTC
I downloaded your project and followed the instructions.  The playground gives the module not found err on any pod included.

What am I missing?

**Comment by neonichu** [comment] 2016-06-14 21:06
You could try deleting DerivedData, that has helped some folks. Which Xcode version are you using?

**Comment by dhf0820** [comment] 2016-06-14 21:12
7.3.1

**Comment by cihadturhan** [comment] 2016-06-15 10:18
Same here. Please let me know if you had any progress

**Comment by codefriar** [comment] 2016-06-18 21:19
Deleting DerivedData worked for me.

**Comment by cihadturhan** [comment] 2016-06-19 00:20
Hello again, I found the solution after one and a half days of testing. Will explain if anyone still needs a help

**Comment by codefriar** [comment] 2016-06-19 00:23
Yes please do explain,

Deleting the derived data seemed to work, but in the end didn’t

**Comment by cihadturhan** [comment] 2016-06-19 07:56
Check your pod version. If it's <1.0 update it.

**Comment by codefriar** [comment] 2016-06-21 18:55
sadly, that's not a working solution for me.

**Comment by dhf0820** [comment] 2016-06-21 20:02
I attempted the same solution and it fails to import any pods.  The pods do work in the actual app though.

dhf

**Comment by cihadturhan** [comment] 2016-06-21 20:07
I can provide some screenshots when I'm on Mac

**Comment by AlexKel** [comment] 2016-06-29 07:52
Hello,

I've had the same issue.. Cleaned project, derived data and re-started Xcode - still was getting the same error. Then I noticed that my iPhone was selected as a target to build for.. the moment I switched that to simulator my warning has gone. I'm not sure if it's just the target device or a combination of all these steps that fixed it for me. Hope this helps someone.

**Comment by neonichu** [comment] 2016-06-29 08:30
@AlexKel thanks, that's a good point — I never noticed this as a potential source of errors because I almost never have my phone attached. Will update the comment at the top of the playground to reflect this.

**Comment by OreniOS** [comment] 2016-06-29 09:28
Well, sorry to say that I tried all of the above and nothing worked.
Cleaned derived data, cleaned project, cleaned build folder, changed devices, closed Xcode, checked pods version, restarted my mac, went to space and came back, got married, had kids and watched the minions movie five times. Doesn't work :/

**Comment by cihadturhan** [comment] 2016-07-06 22:22
Sorry for the late response. When I fix my bug, I learned the hard way but I think some of your solutions will be the same. 

The first thing you should check is the built path of your libraries. Are all the binaries there? Look for the folder of _DerivedData/Name_of_your_project_with_some_id/_ and check the binaries under Build folder. All the frameworks should be under Debug/iPhoneOS or Release/iPhoneOS (iPhoneOS or simulator if you use simulator for building). If you don't see all of your frameworks there after a successful build then you should check the build paths under projects settings for each pod target on xCode. 

Hope that helps someone

**Comment by shepting** [comment] 2016-07-12 17:36
I've hit the same issue, and I hypothesize that the issue is the Framework in question isn't a dynamic library, but rather a static library inside the same framework structure. The pod I'm testing with is `TwitterKit`.

**Comment by nemexyz** [comment] 2016-08-02 15:15
@AlexKel thanks... Device selection is the solution. DeriveData change the directory and delete data locally to build. Worked in 7.3.1.

**Comment by neonichu** [comment] 2016-08-21 19:53
Closing this, because I don't see anything actionable.

**Closed as completed by neonichu** 2016-08-21 19:53 UTC
